### ISSUE TITLE
变量

### ISSUE THREAD

**Issue by wzy6101419** [aaixy/rmmv-plugins#1]
就是我想说 一些道具 通过兑换码获得（正规途径）  通过非法获得 的旧没这变量

自己 2019/11/12 11:42:31
这样他们获取的就可以判断为作弊

自己 2019/11/12 11:43:29
就是这个变量可以多个   这样就可以关联对应的 道具了

**Comment by aaixy** [comment]
已实现

**Comment by aaixy** [comment]
已上传
