### ISSUE TITLE
执行公共事件的兑换码

### ISSUE THREAD

**Issue by aaixy** [aaixy/rmmv-plugins#2]
兑换码直接执行公共事件，除了可以获得道具，还可以显示获得了什么内容，能做什么，如何使用等等等等。
现在仅获得道具，把道具获得提醒关闭了，玩家甚至不知道兑换码使用后发生了什么。但打开道具获得吧，又和原本的道具获得效果重叠显示了。

**Comment by he-cm** [comment]
没看懂


---原始邮件---
发件人: &quot;aaixy&quot;<notifications@github.com&gt;
发送时间: 2019年11月16日(星期六) 下午3:32
收件人: &quot;aaixy/rmmv-plugins&quot;<rmmv-plugins@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: [aaixy/rmmv-plugins] 执行公共事件的兑换码 (#2)



兑换码直接执行公共事&#x4EF6;，除了可以获得道具，还可以显示获得了什么内容，能做什么，如何使用等等等等。
 现在仅获得道具，把道具获得提醒关闭了，玩家甚至不知道兑换码使用后发生了什么。但打开道具获得吧，又和原本的道具获得效果重&#x53E0;显示了。
 
&mdash;

**Comment by aaixy** [comment]
已实现

**Comment by he-cm** [comment]
兑换码?


---原始邮件---
发件人: &quot;aaixy&quot;<notifications@github.com&gt;
发送时间: 2019年11月16日(星期六) 晚上8:03
收件人: &quot;aaixy/rmmv-plugins&quot;<rmmv-plugins@noreply.github.com&gt;;
抄送: &quot;Comment&quot;<comment@noreply.github.com&gt;;&quot;he-cm&quot;<3253421251@qq.com&gt;;
主题: Re: [aaixy/rmmv-plugins] 执行公共事件的兑换码 (#2)



已实现
 
&mdash;

**Comment by he-cm** [comment]
大佬兑换码不对啊


---原始邮件---
发件人: &quot;aaixy&quot;<notifications@github.com&gt;
发送时间: 2019年11月16日(星期六) 晚上8:03
收件人: &quot;aaixy/rmmv-plugins&quot;<rmmv-plugins@noreply.github.com&gt;;
抄送: &quot;Comment&quot;<comment@noreply.github.com&gt;;&quot;he-cm&quot;<3253421251@qq.com&gt;;
主题: Re: [aaixy/rmmv-plugins] 执行公共事件的兑换码 (#2)



已实现
 
&mdash;
